---
- name: 'Copy .tmux.conf to /home/{{ username }}'
  copy:
    src: '.tmux.conf'
    dest: '/home/{{ username }}'

- name: Install tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '/home/{{ username }}/.tmux/plugins/tpm'

- name: Install Plugin using tpm
  command: 'tmux source /home/{{ username }}/.tmux.conf'
