---
- name: 'Copy .vimrc to /home/{{ username }}'
  copy:
    src: '.vimrc'
    dest: '/home/{{ username }}'

- name: https://github.com/VundleVim/Vundle.vim
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '/home/{{ username }}/.vim/bundle/Vundle.vim'

- name: Install Plugin using vundle
  command: vim +PluginInstall +qall

- name: Config YouCompleteMe
  copy:
    src: '.ycm_extra_conf.py'
    dest: '/home/{{ username }}/.vim/bundle/YouCompleteMe'
