---
- name: Create qemu-img
  shell: |
      qemu-img create -f qcow2 /var/lib/libvirt/images/{{ VMName1 }}.qcow2 10G
      qemu-img create -f qcow2 /var/lib/libvirt/images/{{ VMName2 }}.qcow2 10G
      qemu-img create -f qcow2 /var/lib/libvirt/images/{{ VMName3 }}.qcow2 10G

- name: Make preparation for installation
  shell: |
      cp {{ ansible_path }}/repository/{{ ISOName }} {{ ISOPath }} -f
      cp {{ ansible_path }}/config/centos/* /tmp -f
      mount /tmp/{{ ISOName }} /mnt
      cp /mnt/images/pxeboot/vmlinuz /var/lib/libvirt/boot -f
      cp /mnt/images/pxeboot/initrd.img /var/lib/libvirt/boot -f
      umount /mnt

- name: Build Simple HTTP Server
  shell: |
      cd /tmp
      nohup python -m SimpleHTTPServer > simplehttpserver.out 2>&1 &
  async: 300
  poll: 0

- name: Start to install centos-01
  shell: |
      virsh create /tmp/install_01.xml
      sleep 500
      virsh define /tmp/boot_01.xml
      virsh start {{ VMName1 }}
  async: 500
  poll: 0

- name: Start to install centos-02
  shell: |
      virsh create /tmp/install_02.xml
      sleep 500
      virsh define /tmp/boot_02.xml
      virsh start {{ VMName2 }}
  async: 500
  poll: 0

- name: Start to install centos-03
  shell: |
      virsh create /tmp/install_03.xml
      sleep 500
      virsh define /tmp/boot_03.xml
      virsh start {{ VMName3 }}
  async: 500
  poll: 0

- name: Waste time
  command: sleep 500
