---
- name: Build Simple HTTP Server
  shell: |
      cd /tmp
      nohup python -m SimpleHTTPServer > simplehttpserver.out 2>&1 &
  async: 300
  poll: 0

- name: Make preparation for installation
  shell: |
      cp {{ ansible_path }}/repository/{{ ISOName }} {{ ISOPath }} -f
      cp {{ ansible_path }}/config/centos/* /tmp -f
      mount /tmp/{{ ISOName }} /mnt
      cp /mnt/images/pxeboot/vmlinuz /var/lib/libvirt/boot -f
      cp /mnt/images/pxeboot/initrd.img /var/lib/libvirt/boot -f
      umount /mnt

- name: Prepare to install templates
  template: src=install.xml dest=/tmp/{{ item.name }}_install.xml
  with_items:
      - "{{ VMGuest }}"

- name: Prepare to boot templates
  template: src=boot.xml dest=/tmp/{{ item.name }}_boot.xml
  with_items:
      - "{{ VMGuest }}"

- name: Start to install centos
  shell: |
      qemu-img create -f qcow2 /var/lib/libvirt/images/{{ item.name }}.qcow2 10G
      virsh create /tmp/{{ item.name }}_install.xml
  with_items:
      - "{{ VMGuest }}"
  async: 900
  poll: 0

- name: Get centos status while installing
  command: virsh list --name
  register: status
  until: status.stdout.find("{{ item.name }}") == -1
  with_items:
     - "{{ VMGuest }}"
  retries: 30
  delay: 30

- name: Boot centos installed
  shell: |
      sleep 10
      virsh define /tmp/{{ item.name }}_boot.xml
      virsh start {{ item.name }}
  with_items:
      - "{{ VMGuest }}"
