#!/usr/bin/env expect

set args [lindex $argv 0];

if { $args eq "centos" } {
	puts "centos install"
	set playbook "installCentOS"
}
if { $args eq "hadoop" } {
	puts "hadoop install"
	set playbook "installHadoop"
} 

spawn cp playbook/${playbook}.yml . -f
interact

spawn ansible-playbook -i hosts ${playbook}.yml --ask-pass
expect "password:"
send "root\r"
interact

spawn rm ${playbook}.yml
interact
